// SPDX-FileCopyrightText: 2012-2026 Open Assessment Technologies S.A.
// Copyright (C) 2020 Open Assessment Technologies SA;
//
// SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-TAO-Commercial-License

import ariaFactory from './../ariaHelper.js';

const choices = [
    {
        key: 'choice_key_1',
        objectLabel: 'choice_label_1'
    },
    {
        key: 'choice_key_2',
        objectLabel: 'choice_label_2'
    },
    {
        key: 'choice_key_3',
        objectLabel: 'choice_label_3'
    }
];
let freeChoices = choices;
const gaps = [
    {
        key: 'gap_key_1',
        hotspotLabel: 'gap_label_1'
    },
    {
        key: 'gap_key_2',
        hotspotLabel: 'gap_label_2'
    },
    {
        key: 'gap_key_3',
        hotspotLabel: 'gap_label_3'
    }
];
const gapKeysInAriaOrder = ['gap_key_1', 'gap_key_2', 'gap_key_3'];
const choiceKey = 'choice_key_1';
const gapKey = 'gap_key_2';

const msg = ariaFactory();

describe('test accessibility messages', () => {
    it('test message generated by getChoiceAriaLabel', () => {
        const message = msg.getChoiceAriaLabel(choices[2], freeChoices);
        expect(message).toEqual('choice_label_3 option 3');
    });
    it('test message generated by getAnswerAriaLabel', () => {
        const message = msg.getAnswerAriaLabel(gaps[0], choices[0], gapKeysInAriaOrder);
        expect(message).toEqual('gap_label_1 gap 1, filled with choice_label_1');
    });
    it('test message generated by getGapAriaLabel', () => {
        const gapUsageCount = 2;
        const message = msg.getGapAriaLabel(gaps[0], gapKeysInAriaOrder, gapUsageCount);
        expect(message).toEqual('gap_label_1 gap 1. Partially filled');
    });
    it('test message generated by getRemoveAriaLabel', () => {
        const message = msg.getRemoveAriaLabel(choices[0]);
        expect(message).toEqual('Return choice_label_1 to the available options');
    });
    it('test message generated by getChoiceDescribedBy', () => {
        const message = msg.getChoiceDescribedBy();
        expect(message).toEqual(
            'Press enter or space to grab and browse the answer area. To move to next available option, use the arrow keys.'
        );
    });
    it('test message generated by getAnswerDescribedBy', () => {
        const message = msg.getAnswerDescribedBy();
        expect(message).toEqual('Press enter or space to grab. To move to next available answer, use the arrow keys.');
    });
    it('test message generated by getGapDescribedBy', () => {
        const message = msg.getGapDescribedBy();
        expect(message).toEqual(
            'Press enter or space to place down. To browse other gaps use the arrow keys. Press escape to cancel.'
        );
    });
    it('test message generated by announcePlaced', () => {
        const message = msg.announcePlaced(choiceKey, gapKey, choices, freeChoices, gaps, gapKeysInAriaOrder);
        expect(message.text).toEqual('choice_label_1 option 1 has been placed in gap_label_2 gap 2');
        freeChoices = [];
        expect(message.text).toEqual('choice_label_1 option 1 has been placed in gap_label_2 gap 2');
    });
    it('test message generated by announceFull', () => {
        let isFocusOnAnswer = true;
        let message = msg.announceFull(isFocusOnAnswer);
        expect(message.text).toEqual('Answer area is full. To return an answer use the arrow keys.');
        isFocusOnAnswer = false;
        message = msg.announceFull(isFocusOnAnswer);
        expect(message.text).toEqual('Answer area is full. To move to the answer area press Tab');
    });
    it('test message generated by announceRemoved', () => {
        const message = msg.announceRemoved(choiceKey, choices);
        expect(message.text).toEqual('choice_label_1 has been returned to available options');
    });
    it('test message generated by announceCancelled', () => {
        const message = msg.announceCancelled(choiceKey, choices, freeChoices);
        expect(message.text).toEqual('choice_label_1 has not been placed.');
        freeChoices = [];
        expect(message.text).toEqual('choice_label_1 has not been placed.');
    });
});
