# SPDX-FileCopyrightText: 2012-2026 Open Assessment Technologies S.A.
#
# SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-TAO-Commercial-License

files:
  - source: packages/deliver-app/locale/*.pot
    translation: /packages/deliver-app/locale/%locale%/%file_name%.po
