// SPDX-FileCopyrightText: 2012-2026 Open Assessment Technologies S.A.
// Copyright (C) 2025 (original work) Open Assessment Technologies SA
//
// SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-TAO-Commercial-License

/**
 * Look for the style generated by the Authoring's "Style Editor"
 * Create new rules to adapt this style to our item-runner.
 * Return these new rules.
 * @param {CSSRuleList} cssRules
 * @returns {CSSRuleList?}
 */
export function applyStyleEditorTheme(cssRules) {
    if (!cssRules) {
        return void 0;
    }

    const itemRunnerVarsScope = '.qti-item';
    const styleEditorVarsScope = itemRunnerVarsScope;

    for (const rule of Object.values(cssRules)) {
        const newProps = [];
        if (rule.selectorText === styleEditorVarsScope) {
            const style = rule.style;

            for (let i = 0; i < style.length; i++) {
                const propertyName = style[i];
                const propertyValue = `var(${propertyName})`;
                const resolvedPropertyValue = style.getPropertyValue(propertyName);

                switch (propertyName) {
                    case '--styleeditor-font-size': {
                        newProps.push(`--fontsize-body: ${propertyValue}`);
                        newProps.push(`--fontsize-body-xs: calc(${propertyValue} * 0.75)`);
                        newProps.push(`--fontsize-body-s: calc(${propertyValue} * 0.875)`);
                        newProps.push(`--fontsize-heading: ${propertyValue}`);
                        newProps.push(`--fontsize-heading-l: calc(${propertyValue} * 1.25)`);
                        newProps.push(`--fontsize-heading-xl: calc(${propertyValue} * 1.875)`);
                        newProps.push(`--fontsize-heading-xxl: calc(${propertyValue} * 2.5)`);

                        newProps.push(`--styleeditor-font-size-initial: ${resolvedPropertyValue}`);
                        break;
                    }
                    case '--styleeditor-font-family': {
                        newProps.push(`--font-ui: ${propertyValue}`);
                        break;
                    }
                    case '--styleeditor-bg-color': {
                        newProps.push(`--color-bg-default: ${propertyValue}`);
                        newProps.push(`--color-bg-input-default: ${propertyValue}`);
                        newProps.push(`--color-bg-actionable-secondary: ${propertyValue}`);
                        break;
                    }
                    case '--styleeditor-text-color': {
                        newProps.push(`--color-text-default: ${propertyValue}`);
                        newProps.push(`--color-text-feedback: ${propertyValue}`);
                        newProps.push(`--color-link-primary: ${propertyValue}`);
                        break;
                    }
                    case '--styleeditor-border-color': {
                        newProps.push(`--color-border-default: ${propertyValue}`);
                        newProps.push(`--color-border-input-default: ${propertyValue}`);
                        newProps.push(`--color-border-default: ${propertyValue}`);
                        newProps.push(`--color-border-info: ${propertyValue}`);
                        break;
                    }
                    case '--styleeditor-table-heading-bg-color': {
                        newProps.push(`--color-bg-table-heading: ${propertyValue}`);
                        break;
                    }
                    default:
                        break;
                }
            }

            const newStylesheet = new CSSStyleSheet();

            addA11yOverrideRules(newStylesheet, styleEditorVarsScope);

            newStylesheet.insertRule(`${itemRunnerVarsScope} {${newProps.join(';')}}`);
            for (const existingRule of cssRules) {
                try {
                    // rules like @import now throw
                    newStylesheet.insertRule(existingRule.cssText);
                } catch(err) {
                    console.error(err);
                }
            }

            return newStylesheet.cssRules;
        }
    }
    return void 0;
}

/**
 * Test-runner's 'a11y' plugin should override StyleEditor's styles.
 * Add some rules to support that.
 * @param {CSSStyleSheet} newStylesheet - rules are appended to it
 * @param {String} styleEditorVarsScope
 */
function addA11yOverrideRules(newStylesheet, styleEditorVarsScope) {
    // FontFamilySetting: unset StyleEditor font-family
    const fontFamilyScope = '[data-a11y-override-font-family="true"]';
    const fontFamilyValues = '--styleeditor-font-family: unset';
    newStylesheet.insertRule(`${fontFamilyScope} ${styleEditorVarsScope} {${fontFamilyValues}}`);

    // FontSizeSetting: scale StyleEditor font-size relatively
    const fontSizeScope = '[data-a11y-override-font-size="true"]';
    const fontSizeValues =
        '--styleeditor-font-size: calc(var(--styleeditor-font-size-initial) * var(--a11y-fontsize-scale, 1))';
    newStylesheet.insertRule(`${fontSizeScope} ${styleEditorVarsScope} {${fontSizeValues}}`);
}
